### ISSUE TITLE
improve cloudant changes feed error handling (especially for bogus host or dbname)

### ISSUE THREAD

**Issue by johnsolm** [openwhisk/openwhisk-package-cloudant#21]
when creating a cloudant.changes trigger, if one provides a dbname that does not exist, cloudant now rejects the request. but the openwhisk changes action does not propagate this error through in a way that allows a user to know what went wrong:

firstly, the statusCode is 502, which implies author error, i.e. in some code i wrote (because i get the same 502 e.g. if i have a typo in my action source), whereas this is a case of invoker error. i don't think we have error codes that distinguish between author error and invoker error.

secondly, the response body has no logs or error text that'd help intuit what went wrong:
```
{"name":"changes","subject":"lime@us.ibm.com","activationId":"9b6bce0c279940b6
b830eed71e5ceb12","publish":false,"annotations":[],"version":"0.0.45","response":{"result":{"error":null},"success":false,"status":"application error"},"end":
1467120637640,"logs":[],"start":1467120637039,"namespace":"lime@us.ibm.com"}
```

@markus-thoemmes found the underlying backend log (that does **not** appear in what the client sees):

```
[2016-06-28T13:30:37.644Z] [ERROR] [??] [addDataTrigger] Error occurred for trigger /uitest3_uitest3/whisk_system-cloudant-changes_nodejs__trigger (db xxx): {"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"xxx"}`
```

pragmatic suggestion: at the very least, the `errno:ENOTFOUND` should be passed through to the client; better, perhaps, would be to pass through the entire error response. in this case, the error was actually not in the dbname, but in the hostname; i.e. the `getaddrinfo` syscall failed to find hostname xxx.

ideal suggestion: changes should interpret syscall==getaddrinfo && errno==ENOTFOUND as "hostname field invalid"; similarly, for whatever error cloudant passes back for a bogus dbname, the response should be "dbname field invalid".

**Comment by johnsolm** [comment]
Due 11/11

**Comment by jasonpet** [comment]
@johnsolm - is this done?
