### ISSUE TITLE
includeDocs getting set to 'false' string

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk-package-cloudant#28]
The code in initTrigger from util.js contains the following
```
        if (obj.includeDoc) {
            includeDoc = ((obj.includeDoc === true || obj.includeDoc.toString().trim().toLowerCase() === 'true')) || 'false';
        }
```

includeDocs is getting set to string 'false' instead of boolean `false`
Needs to be change to 
```
        if (obj.includeDoc) {
            includeDoc = ((obj.includeDoc === true || obj.includeDoc.toString().trim().toLowerCase() === 'true')) || false;
        }
```

**Comment by johnsolm** [comment]
actually needn't be set at all, and is not getting used anymore.

**Comment by johnsolm** [comment]
we still will reference include docs but only to warn user in the even they set it.

**Comment by csantanapr** [comment]
The whole line can be removed. and just save obj.includeDoc as it comes out of the DB

**Comment by jasonpet** [comment]
yeah, I already updated as part of https://github.com/openwhisk/openwhisk-package-cloudant/pull/31
