### ISSUE TITLE
list documents doesn't support include docs

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk-package-cloudant#52]
the action for listing docs in a db doesnt offer the include docs option.

**Comment by timwis** [comment]
Yeah, it looks like support for `includeDoc` was removed. Anyone know why?

**Comment by csantanapr** [comment]
Closing as you can pass any parameter you want to db.list https://github.com/cloudant-labs/cloudant-nano#dblistparams-callback

wsk action invoke mycloudant/list-documents -p params "{\"include_docs\":true}"
