### ISSUE TITLE
remove Include Docs option

### ISSUE THREAD

**Issue by johnsolm** [openwhisk/openwhisk-package-cloudant#8]
remove ability to include docs

**Comment by jasonpet** [comment]
It was determined that we should remove this option.  However, we need to handle the scenario for existing triggers that had set this to true.  Need to produce some type of error message for user stating this is no longer supported.  Should also create tutorial on how user can fetch docs.

**Comment by johnsolm** [comment]
Due 11/10

**Comment by jasonpet** [comment]
resolved by PR https://github.com/openwhisk/openwhisk-package-cloudant/pull/23
