### ISSUE TITLE
update backoff strategy to be exponential

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk-package-cloudant#89]
The strategy backoff currently is linear with default values of 1second delay with 10 retries.

It should use an [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) instead.
With default values of 10seconds defayl with 10 retries.

Because of OpenWhisk rate limit on trigger limits, it will return 429 statusCode.
OpenWhisk window for the rate limit is 1 minute.

I would make it on first 429 delay for 1 minute, if after 1 minute delay there is a another 429 then I would start exponential back off of 10 seconds (i.e. 10s, 40s, 90s, 160s. etc..)

**Comment by jasonpet** [comment]
resolved by PR #90
