### ISSUE TITLE
Manage Socket Connection Settings

### ISSUE THREAD

**Issue by johnsolm** [openwhisk/openwhisk-package-cloudant#9]

**Comment by johnsolm** [comment]
might need to pull this out.  have some code clean up if i need to remove this logic.

**Comment by johnsolm** [comment]
Pulled out all references to this until I talk to Carlos

**Comment by jasonpet** [comment]
@johnsolm - what is the status of this?

**Comment by johnsolm** [comment]
this is no longer getting done.  the socket connection update I was implementing did not improve performance since it was only applied to a connection for a single trigger.
